### ISSUE TITLE
Create a xUnit like report formatter plugin

### ISSUE THREAD

**Issue by virgs** [enqueuer-land/plugins-list#1]
XUnit is one of the most widely supported formats for recording test results.
Many CI servers accept JUnit XML as their de facto standard for reporting test results, this makes this plugin ideal for reporting results to them.

Create a plugin like this [one](https://github.com/enqueuer-land/enqueuer-plugin-html-report)

These links may help:
[junit-xml-format-to-jenkins](https://stackoverflow.com/questions/4922867/what-is-the-junit-xml-format-specification-that-hudson-supports)
[junit-xsd](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd)

**Comment by williamsdevaccount** [comment]
I should be able to do that. I have worked with xml2j and xml-builder in node so I should be able to get out a v1 plug-in relatively quickly so we can discuss the report format and make adjustments as needed.

**Comment by virgs** [comment]
Great. Thank you very much.
Looking forward to see it integrated with some CI server.

**Comment by williamsdevaccount** [comment]
https://github.com/williamsdevaccount/enqueuer-plugin-xunit-report


Here is the first implementation of the xunit reporter. I have unit tests within the plugin and I have the project hooked up to travis CI to perform automated builds.

**Comment by virgs** [comment]
It look's awesome.
That was impressively fast.
I think we can close this issue and keep the conversation going in that repository.
Consider adding it to [plugins list](https://github.com/enqueuer-land/plugins-lis)

**Comment by williamsdevaccount** [comment]
It has been added!
